---
title: "Gen_art"
author: "Daniel Boppert"
date: "2023-11-11"
output: html_document
---

```{r setup, include=FALSE}
packages <- c('dplyr', 'ggplot2', 'tidyverse', 'devtools', 'generativeart', 'ambient', 'mathart', 'ggforce', 'Rcpp') #Loading the necessary packages into a vector

# Loading all packages.
lapply(packages, library, character.only = TRUE) # Calling the vector
```

```{r, echo = TRUE, include = TRUE}
# generative art package

# set the paths
IMG_DIR <- "images/"
IMG_SUBDIR <- "everything/"
IMG_SUBDIR2 <- "handpicked/"
IMG_PATH <- paste0(IMG_DIR, 
                   IMG_SUBDIR)
LOGFILE_DIR <- "logfile/"
LOGFILE <- "logfile.csv"
LOGFILE_PATH <- paste0(LOGFILE_DIR, 
                       LOGFILE)
# create the directory structure
generativeart::setup_directories(IMG_DIR, 
                                 IMG_SUBDIR, 
                                 IMG_SUBDIR2, 
                                 LOGFILE_DIR)
# include a specific formula, for example:
my_formula <- list(
  x = quote(runif(1, -1, 10) * x_i^2 - sin(y_i^2)),
  y = quote(runif(1, -1, 10) * y_i^3 - cos(x_i^2) * y_i^4)
)
# call the main function to create five images with a polar coordinate system
generativeart::generate_img(formula = my_formula, 
                            nr_of_img = 5, # set the number of iterations
                            polar = TRUE, 
                            filetype = "png", 
                            color = "#c1a06e", 
                            background_color = "#1a3657")
```

```{r}
# ggart

# devtools::install_github("marcusvolz/mathart")
# devtools::install_github("marcusvolz/ggart")
points <- mathart::points
result <- kdtree(points)
p1 <- ggplot() +
  geom_segment(aes(x, y, xend = xend, yend = yend), result) +
  coord_equal() +
  xlim(0, 15000) + ylim(0, 15000) +
  theme_blankcanvas(bg_col = "#fafafa", margin_cm = 0)
# save plot
ggsave("kdtree.png", p1, width = 20, height = 20, units = "in")

p1

```



```{r}
set.seed(123)

terminals <- data.frame(x = runif(10, 0, 10000), y = runif(10, 0, 10000))

df <- 1:10000 %>%
  map_df(~weiszfeld(terminals, c(points$x[.], points$y[.])), .id = "id")

p <- ggplot() +
  geom_point(aes(x, y), points, size = 1, alpha = 0.25) +
  geom_point(aes(x, y), terminals, size = 5, alpha = 1) +
  geom_line(aes(x, y, group = id), df, colour = "black", size = 0.5, alpha = 0.03) +
  coord_equal() +
  xlim(0, 10000) +
  ylim(0, 10000) +
  theme_blankcanvas(margin_cm = 0)

ggsave("weiszfeld.png", p, width = 20, height = 20, units = "in")

p
```
